#pragma config(Sensor, S1,     rs,             sensorEV3_Color)
#pragma config(Sensor, S4,     ls,             sensorEV3_Color)
#pragma config(Motor,  motorA,          rm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          lm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn_right(int num){
	int turn =0;
	nMotorEncoder[lm]=0;
	while(turn <= num){
		turn = getMotorEncoder(lm);
		setMotorSpeed(lm,100);
		setMotorSpeed(rm,-100);
	}
}
void turn_left(int num){
	int turn =0;
	nMotorEncoder[rm]=0;
	while(turn <= num){
		turn = getMotorEncoder(rm);
		setMotorSpeed(rm,100);
		setMotorSpeed(lm,-100);
	}
}

void line_following(){
	int speed = 100;
	int thl = 10;
	int thr = 10;

	if(SensorValue(ls)>thl&&SensorValue(rs)>thr){
		setMotorSpeed(lm,speed);
		setMotorSpeed(rm,speed);
	}
	if(SensorValue(ls)<=thl&&SensorValue(rs)>thr){
		setMotorSpeed(lm,0);
		setMotorSpeed(rm,speed);
	}
	if(SensorValue(ls)>thl&&SensorValue(rs)<=thr){
		setMotorSpeed(lm,speed);
		setMotorSpeed(rm,0);
	}
}

task main()
{
	int count =0;
	int thl = 10;
	int thr = 10;

	while(true){
		line_following();
		if(SensorValue(ls)<=thl&&SensorValue(rs)<=thr){
			setMotorSpeed(lm,100);
			setMotorSpeed(rm,100);
			delay(300);
			count++;
		}
		if(count==2||count==5){
			turn_left(460);
			count++;
		}
	}
}
